version: '3.5'
services:

    redis:
      container_name: redis
      image: redis
      restart: always
      ports:
        - "6379:6379"
      volumes:
        - redis-data:/data

    migration:
      build: .
      command: bash -c "python manage.py makemigrations chat && python manage.py migrate"
      volumes:
        - .:/django_chat_room

    app:
      build: .
      command: bash -c "python manage.py runserver 0.0.0.0:8000"
      restart: always
      ports:
        - "8000:8000"
      volumes:
        - .:/django_chat_room
      depends_on:
        - redis

volumes:
    redis-data:
